Repository TheAlgorithms/website, pull requests merged in 2021-06, with the labels that each got.

#88 Pull request template added
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#89 Add Info about Plausible
  components/footer/index.tsx
  package.json
  pages/plausible.tsx
  public/locales/en/common.json
  yarn.lock
Labels: approved, enhancement

#87 Improve languages list
  components/categoriesList/index.tsx
  components/editPage/addImplementation/index.tsx
  components/implementations/index.tsx
  components/languagesList/index.tsx
  components/languagesList/style.module.css
  lib/stars.ts
  package.json
  pages/index.tsx
  scripts/fetch-algorithms.ts
  yarn.lock
Labels: approved, enhancement

#90 Add CSS effects in the `algorithmCard`
  components/algorithmsList/algorithmCard/index.tsx
  components/categoriesList/index.tsx
  components/categoriesList/style.module.css
  styles/globals.css
Labels: enhancement

#98 Fix too long algorithm name wrapping on card
  components/algorithmsList/algorithmCard/index.tsx
  components/algorithmsList/algorithmCard/style.module.css
Labels: approved, bug

#100 Fix a bug in dark mode introduced in #98
  components/algorithmsList/algorithmCard/style.module.css
Labels: approved, enhancement, good first issue

#70 add contributors
  components/contributors/dialog/index.tsx
  components/contributors/dialog/style.module.css
  components/contributors/index.tsx
  components/contributors/style.module.css
  hooks/search.ts
  lib/models.ts
  package.json
  pages/algorithm/[algorithm].tsx
  scripts/fetch-algorithms.ts
  styles/globals.css
  yarn.lock
Labels: enhancement

#102 Revert to next.js 10
  package.json
  yarn.lock
Labels: bug
