Repository TheAlgorithms/website, pull requests merged in 2021-05, with the labels that each got.

#72 feat: Translation support and minor improvements for #71
  components/editPage/addExplanation/index.tsx
  components/editPage/addImplementation/index.tsx
  components/editPage/addTranslation/index.tsx
  components/editPage/index.tsx
  components/icon/index.tsx
  components/implementations/index.tsx
  components/langSelect/index.tsx
  components/translation.tsx
  package.json
  pages/index.tsx
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/eo/common.json
  public/locales/es/common.json
  public/locales/hr/common.json
  public/locales/uk/common.json
  yarn.lock
Labels: approved, enhancement, translations

#71 Add links to edit the page at the bottom of an algorithm page
  components/editPage/addExplanation/index.tsx
  components/editPage/addExplanation/style.module.css
  components/editPage/addImplementation/index.tsx
  components/editPage/addImplementation/style.module.css
  components/editPage/addTranslation/index.tsx
  components/editPage/addTranslation/style.module.css
  components/editPage/index.tsx
  components/editPage/style.module.css
  components/icon/index.tsx
  components/implementations/index.tsx
  components/langSelect/index.tsx
  components/languagesList/style.module.css
  components/translation.tsx
  lib/models.ts
  package.json
  pages/_app.tsx
  pages/algorithm/[algorithm].tsx
  pages/index.tsx
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/eo/common.json
  public/locales/es/common.json
  public/locales/hr/common.json
  public/locales/uk/common.json
  scripts/fetch-algorithms.ts
  yarn.lock
Labels: approved, enhancement

#81 Not found message on invalid search
  pages/search/index.tsx
  public/locales/en/common.json
Labels: enhancement

#83 Added Effects on outercardbox
  components/categoriesList/style.module.css
Labels: approved, enhancement

#78 Remove CodeQL and replace it with tsc and eslint
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
Labels: enhancement

#77 Improve seo
  components/algorithmsList/algorithmCard/index.tsx
  components/algorithmsList/index.tsx
  components/codePreview/index.tsx
  components/editPage/addExplanation/index.tsx
  components/editPage/addImplementation/index.tsx
  components/editPage/addTranslation/index.tsx
  components/editPage/index.tsx
  components/footer/index.tsx
  components/head.tsx
  components/implementations/index.tsx
  components/jumbo/index.tsx
  components/navbar/index.tsx
  components/searchBar/index.tsx
  components/translation.tsx
  hooks/search.ts
  hooks/translation.ts
  pages/404.tsx
  pages/_document.tsx
  pages/algorithm/[algorithm].tsx
  pages/all.tsx
  pages/category/[category].tsx
  pages/index.tsx
  pages/language/[language].tsx
  pages/search/index.tsx
  public/locales/en/common.json
Labels: enhancement

#84 Update Background
  components/jumbo/index.tsx
  components/jumbo/renderedBackgrounds.ts
  components/jumbo/style.module.css
  public/programming-1873854.webp
Labels: approved, enhancement
