Repository TheAlgorithms/website, pull requests merged in 2021-11, with the labels that each got.

#129 Use translated string for the `Code Playground` string
  layouts/playground/index.tsx
Labels: translations

#128 New Code View
  .eslintignore
  .gitignore
  .vercelignore
  components/codePreview/index.tsx
  components/codePreview/style.module.css
  components/icon/index.tsx
  pages/algorithm/[algorithm].tsx
  public/locales/en/common.json
Labels: enhancement, approved

#132 feat(playground): load packages and add xterm
  components/playgroundEditor/index.tsx
  components/playgroundEditor/style.module.css
  lib/pyodide.ts
  package.json
  pages/playground.tsx
  public/locales/en/categories.json
  public/locales/en/common.json
  scripts/fetch-algorithms.ts
  yarn.lock
Labels: enhancement, approved

#133 Disable blank issues and add Discord community information
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#134 Update the Code of Conduct to the latest version
  CODE_OF_CONDUCT.md
Labels: documentation

#135 feat: Improve the issue templates/forms
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/content-issue.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/ISSUE_TEMPLATE/translation-issue.yml
Labels: documentation, approved

#137 Update the Gitpod file with tweaks
  .gitpod.yml
Labels: enhancement

#140 Add some Open Graph Meta tags
  components/head.tsx
Labels: enhancement, approved

#136 More Languages for Code Playground
  components/codePreview/index.tsx
  components/playgroundEditor/index.tsx
  hooks/translation.ts
  lib/playground/codeRunner.ts
  lib/playground/index.ts
  lib/playground/pistonCodeRunner.ts
  lib/playground/pythonCodeRunner.ts
  lib/pyodide.ts
  tsconfig.json
Labels: enhancement

#141 feat: Add `og:locale`
  components/head.tsx
Labels: enhancement
