Repository TheAlgorithms/website, pull requests merged in 2021-03, with the labels that each got.

#17 Add "Donate" section
  components/footer/index.tsx
  pages/index.module.css
  pages/index.tsx
Labels: approved, enhancement

#18 fix: Move the "Donate" link to the right side in the footer
  components/footer/index.tsx
Labels: approved, enhancement

#15 feat: Update Vercel banner in the footer
  components/footer/index.tsx
  components/footer/style.module.css
  public/powered-by-vercel-t.svg
Labels: approved, enhancement

#19 fix: LGTM alerts/warnings
  components/icon/index.tsx
  pages/algorithm/[slug].tsx
Labels: approved, enhancement

#23 feat: Use a transparent logo in `components/head.tsx`
  components/head.tsx
Labels: approved, enhancement

#24 feat: Add CodeQL Analysis workflow
  .github/workflows/codeql-analysis.yml
Labels: approved, enhancement

#25 feat: Add `Approved Label` workflow
  .github/workflows/approved-label.yml
Labels: approved, enhancement

#29 Translations update from Weblate
  public/locales/nb_NO/index.json
  public/locales/tr/index.json
Labels: enhancement

#30 feat: Add support for more translations and strings
  README.md
  components/categoriesList/index.tsx
  components/footer/index.tsx
  components/jumbo/index.tsx
  components/navbar/index.tsx
  components/searchBar/index.tsx
  pages/index.tsx
  public/locales/en/index.json
  public/locales/es/index.json
Labels: approved, enhancement

#32 Translations update from Weblate
  public/locales/de/common.json
  public/locales/es/common.json
Labels: translations

#36 Translations update from Weblate
  public/locales/es/common.json
Labels: translations

#31 feat: add internationalization
  .gitignore
  README.md
  components/algorithmsList/algorithmCard/index.tsx
  components/footer/index.tsx
  components/jumbo/index.tsx
  components/langSelect/index.tsx
  components/langSelect/style.module.css
  components/navbar/index.tsx
  components/navbar/style.module.css
  components/searchBar/index.tsx
  hooks/smoothScroll.tsx
  lib/algorithms.ts
  lib/aliases.js
  lib/categories.ts
  lib/languages.ts
  lib/locales.js
  lib/models.ts
  next-i18next.config.js
  next.config.js
  package.json
  pages/404.tsx
  pages/_app.tsx
  pages/algorithm/[algorithm].tsx
  pages/all.tsx
  pages/category/[category].tsx
  pages/ideas.tsx
  pages/index.tsx
  pages/language/[language].tsx
  pages/search/index.tsx
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/nb_NO/common.json
  public/locales/tr/common.json
  scripts/fetch-algorithms.ts
  yarn.lock
Labels: approved, enhancement
