Repository TheAlgorithms/website, pull requests merged in 2022-10, with the labels that each got.

#191 [BUG]fix: invalid link generator for `C#` codes.
  scripts/fetch-algorithms.ts
Labels: bug, dont-close, content

#189 feat(locale): added Persian language
  lib/locales.js
  public/flags/fa.svg
Labels: translations

#201 Add Sudoku and Sudoku Solver as an alias
  lib/aliases.ts
Labels: content

#204 fix: multiple content names
  lib/aliases.ts
Labels: content
