Repository TheAlgorithms/website, pull requests merged in 2022-09, with the labels that each got.

#175 `2021` -> `new Date().getFullYear()` in Footer copyright message for automatic year update
  components/footer/index.tsx
Labels: bug

#176 Added og tag for twitter and og-image
  components/head.tsx
  public/og-image.png
Labels: enhancement

#179 Implement ISR
  lib/algorithms.ts
  lib/aws.ts
  lib/categories.ts
  lib/fs.ts
  lib/languages.ts
  lib/walk.ts
  next-i18next.config.js
  package.json
  pages/[shortlink].tsx
  pages/algorithm/[algorithm].tsx
  pages/category/[category].tsx
  pages/language/[language].tsx
  public/locales/en/categories.json
  scripts/fetch-algorithms.ts
  yarn.lock
Labels: enhancement

#182 Replace all `discord.gg` instances with new link
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  components/editPage/addExplanation/index.tsx
  components/editPage/addTranslation/index.tsx
  pages/[shortlink].tsx
  pages/index.tsx
Labels: enhancement, approved

#184 added hindi language
  lib/locales.js
Labels: translations

#186 Use correct Discord invitation link
  pages/[shortlink].tsx
Labels: bug, approved
