Repository TheAlgorithms/website, pull requests merged in 2022-12, with the labels that each got.

#190 Add missing `package.json` fields
  package.json
Labels: enhancement

#213 Added typewriter styling to Hello Algorithms
  components/jumbo/index.tsx
  package.json
  public/locales/en/categories.json
  yarn.lock
Labels: enhancement

#215 Add Arabic to the language list
  components/jumbo/index.tsx
  lib/locales.js
  public/flags/ar.svg
Labels: translations

#214 Remove a few badges
  README.md
Labels: documentation, approved

#217 fix: Anagram aliases
  lib/aliases.ts
Labels: content
